services:
  mysql:
    image: docker.io/library/mysql:8.4
    container_name: lanchonete_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lanchonete_db
      MYSQL_USER: user
      MYSQL_PASSWORD: senhauser
    ports:
      - "3306:3306"
    volumes:
      - lanchonete_data:/var/lib/mysql
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lanchonete_data:
