spring.application.name=lanchonete

# Configurações do banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/lanchonete_db
spring.datasource.username=user
spring.datasource.password=senhauser
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
